### ISSUE TITLE
Running locast as a service modifications

### ISSUE THREAD

**Issue by SJLBoulder** [wouterdebie/locast2dvr#10]
Again thanks for locast2dvr.

I was able to get locast as a service to work by making a couple changes to locast2dvr.service:

1) Probably obvious, but may not be obvious to everyone:  In locast2dvr.service,  "myuser" needs to be change to your username.

2) I was getting "systemd: locast2dvr.service: Failed to execute command: No such file or directory" error message.  I resolved this by adding /bin/bash and adding .sh in the ExecStart command:  "ExecStart=/bin/bash /home/myuser/bin/locast2dvr/locast2dvr_wrapper.sh -c /home/myuser/.locast2dvr/config"

It's now running as a service.

Thanks.

**Comment by wouterdebie** [comment]
Hi!

Thanks for the comments! A few questions:

1. I figured that was somewhat obvious, but I'll add it to the readme.
2. Did you `chmod +x /path/to/wrapper/file`? 

Take care!

**Comment by SJLBoulder** [comment]
Hi, wouterdebie.

Yes, I did "chmod +x" the wrapper file.  I'm running PLEX and locast2dvr on Ubuntu 18.04 (Hyper-V VM). I'm not that familiar with Linux, and what I do know is mostly OMVS/Unix System Services (retired IBMer). So, I may have overlooked something. But chasing down the error message led me to that solution, and it worked.

Happy New Year!
