### ISSUE TITLE
Better Integration With Plex

### ISSUE THREAD

**Issue by Croq360** [wouterdebie/locast2dvr#12]
If you have more than one DMA selected, and they share a channel number, that causes problems in Plex.  Plex will only allow a single station per channel (e.g., if you have more than one channel in the 4.1 slot, you can only pick one of them to display).

One option out there is that you can use xTeVe to remap the channels, but when you try to load lineup.m3u from locast2dvr, you get an error stating, "[ERROR] Invalid M3U file, an extended M3U file is required."  Adding #EXTM3U on line 1 of the m3u file fixes the problem, that line is specified as being required by the m3u standard.  I did manage to get the code changed on my side to do that and tested it out in xTeVe and it worked (though you wouldn't want my hacked "fix").  However, it's quite daunting to have so many to modify.

Another option (probably better option for most people) would be to give an option to direct locast2dvr to handle the renumbering.  Perhaps it could do something like maintain the channel numbers for the first location, then for any additional location, increment each by 100.  Doing that, if you had two 4.1 channels, the first would get channel 4.1, the one in the second DMA would get 104.1.

**Comment by wouterdebie** [comment]
Thanks for the feedback! I've fixed the m3u header in 0.4.32. Would you mind seeing if that works?

Regarding Plex though, I kind of moved away from development for that, since Plex is somewhat limited when it comes to handling multiple tuners (or even multiplexing them) and then have the right EPG data to go with that. That said, I'd be more than happy to implement what you are proposing, as long as you can test it out :)

**Comment by Croq360** [comment]
Thanks for the update, I'll check it out and let you know.  Regarding the renumbering (I think that's what you were referring to), yes, I'd be happy to test it out.

**Comment by wouterdebie** [comment]
By the way, are you running this with the multiplexer option?

**Comment by wouterdebie** [comment]
I just added a `--remap/-r` option that should do exactly as you mentioned. It's in version 0.5.0. Would you mind testing it out?

**Comment by Croq360** [comment]
I got a chance to test it out.

First, yes, I'm running the multiplexer option.

Regarding the channel remapping, it seems to be working, but it's only adding the 100/200/etc offsets on channels that have duplicate channel numbers.  What I had hoped for is that the first location would all have their actual channel numbers, the second would have 100 added to every one, not just the duplicate channel numbers, the third would have 200 added, and so on. 
 This way, each location's channels are grouped together.

**Comment by wouterdebie** [comment]
The fix was really simple, so I've changed the code. I'll have a look at yours to make sure it's what you were thinking. Can you try out 0.5.2?

**Comment by Croq360** [comment]
Sure, it'll be a little while, still working.  Yeah, I was able to fix it pretty easily on my end, but then started running into the increment changing from 100/200/300/... to 200/400/600/... to 300/600/900/... and so on with each access of epg.xml.  The changes I made in _remap fixed that so it always does 100/200/300/... for the numbering.

**Comment by wouterdebie** [comment]
Haha, I hadn't even noticed that :) But you're right. I modify state and don't want to remap every single time. This is fixed in 0.5.4. Thanks for the heads-up!

**Comment by Croq360** [comment]
Looks to work perfectly now.  I liked your solution better than mine... :-)

Thanks for the updates over the last few days!
