### ISSUE TITLE
Allow Use of Local Channel Logos

### ISSUE THREAD

**Issue by Croq360** [wouterdebie/locast2dvr#13]
Many of the channel logos being provided through the locast/roku leave something to be desired.  In Emby at least, they show up so small in the guide, that across the room, they're difficult to see.  It seems like Emby would scale the logo bigger to fit in the available space, but that doesn't seem to be happening (or perhaps there's a bunch of dead space around many of the logos which is part of the image, making it not able to scale bigger).

Can locast2dvr be modified to allow us to provide our own defined location for channel logos?  The default could be something like channelName.jpg (e.g., WABCDT.jpg).  If a given logo doesn't exist when it's scanned, then fall back to the default one.

**Comment by wouterdebie** [comment]
I realized I used the small logos from locast (logo226Url from locast data) instead of the nicer ones that locast provides. I've updated 0.4.31 to use those instead and fallback to the smaller ones. Could you see if that works? If not, I might think about a logo override option.

**Comment by Croq360** [comment]
It looks like your change fixed the issue.  It didn't reflect with just a EPG refresh in Emby, so I removed the EPG and DVR and added them back to Emby, and the larger logos appeared.
