### ISSUE TITLE
Optionally add season to EPG XML for Specified Genre

### ISSUE THREAD

**Issue by mpoplaw** [wouterdebie/locast2dvr#16]
Enhancement Idea:

It would be nice if there was an option add a default season (maybe use the current year?) if it doesn't exist to the epg xml for specific listing genre.   In Plex, if there is no season information, it treats the listing as a Movie which means there is no option to record the listing as a series.   An example genre that I cannot record as a series in Plex is:  News

**Comment by wouterdebie** [comment]
Interesting idea! Is there another way to tell Plex that something is not a movie? Adding season information feels a bit like a hack. In the data I get from locast.org there is the field 'showType', which is set to 'Series' for news.

**Comment by wouterdebie** [comment]
by the way, if I look at the [XMLTV example](http://wiki.xmltv.org/index.php/XMLTVFormat), the category has "Series" for news. I'll add and we can see what happens.

**Comment by wouterdebie** [comment]
I've added this in 0.5.7. Would you mind testing this for me? I don't use Plex myself.

**Comment by mpoplaw** [comment]
I’ll test it today when I have a chance and report back, yes.  Thanks.

Also, I’ve searched all over to figure out if there is a way to force plex to identify something as a series and not a movie and I don’t think there is, at least not yet.

I do agree it feels like a hack to inject season & episode information, but If it comes down to that, maybe we have options like...

season options:  <year> | <year>_<month>

episode options:  <month>_<day>_<start time> | <day>_<start time>

**Comment by wouterdebie** [comment]
I've added some more improvements. It seems using `<episode-num system="original-air-date">` and then either the startTime (in case of news) or the actual airDate seems to work well. This is available in version 0.5.8.

I'd be curious to hear your experiences.

**Comment by mpoplaw** [comment]
Good news, in PLEX I can now record a News program as a Series.

This is what I see in the EPG XML now

episode-num for a News program:
`<episode-num system="original-air-date">2021-01-19 00:00:00</episode-num>`

episode-num for a standard series show:
`<episode-num system="xmltv_ns">5.4.</episode-num>`

I think this looks good.  Thank you!

**Comment by wouterdebie** [comment]
It depends. The logic is as follows:

if there's an episode number and season number --> xmltv_ns
if there's an episode number --> xmltv_ns
if the genre is news or it's not a movie but is new --> original-air-date with program start time (includes the hour and mins)
if it's not a movie, but there's an original airdate --> original-air-date with airdate (doesn't include the hour and minutes)

So for news, you should always that the actual start time. Note that all times are in UTC, so I assume that the timestamp you showed was correct. 00:00:00 UTC is 6pm EST.

**Comment by mpoplaw** [comment]
Got it, this makes sense.  I didn’t realize it was UTC, so all zeros is expected!   Your work and explanation is appreciated.
