### ISSUE TITLE
Issue with News Episode UTC Dates

### ISSUE THREAD

**Issue by mpoplaw** [wouterdebie/locast2dvr#19]
So now that the News episode information is encoded with the UTC startTime, my 6pm news episode# is encoded as the following day since UTC is 6 hours ahead of me.  :)   This doesn't affect the ability to record it as a series on Plex, but it is a bit confusing since the episode date doesn't match the local "Air Time".   Is it possible to convert this to a local startTime on the fly?

**Comment by mpoplaw** [comment]
Example:
`<programme start="20210122000000 +0000" stop="20210122003000 +0000" channel="channel.1595365081563">`

` <episode-num system="original-air-date">2021-01-22 00:00:00</episode-num>`

For UTC-6, the air date is actually 1/21, but the episode# is 2021-01-22.

**Comment by mpoplaw** [comment]
Can +0000 be tacked on in the episode-num entry?

something like:
`<episode-num system="original-air-date">2021-01-22 00:00:00 +0000</episode-num>`

**Comment by wouterdebie** [comment]
Absolutely. Let's give that a try and see if it works.

**Comment by wouterdebie** [comment]
I've added this to 0.5.15. Could you test if this works?

**Comment by wouterdebie** [comment]
I also added another system, called dd_progid which should help with determining episodes for a show.

**Comment by mpoplaw** [comment]
Yes, I’ll test this out tonight.  Thanks

**Comment by wouterdebie** [comment]
Much appreciated!

**Comment by mpoplaw** [comment]
I have 0.5.17 installed and something is wrong.  For the program below, the PLEX episode now reads "8/22/05 - Episode 08-22".  I cannot figure out why it thinks this...  could it be the dd_progid?

` <programme start="20210122040000 +0000" stop="20210122043500 +0000" channel="channel.1595533936942">
    <title lang="en">WCCO 4 News at Ten</title>
    <desc lang="en">Local and regional news.</desc>
    <date>20050822</date>
    <category lang="en">News</category>
    <category lang="en">Series</category>
    <length units="seconds">2100</length>
    <icon src="https://fans.tmsimg.com/assets/p984429_b_v5_ab.jpg" height="360" width="240"/>
    <episode-num system="original-air-date">2021-01-22 04:00:00 +0000</episode-num>
    <episode-num system="dd_progid">SH007711120000</episode-num>
    <video>
      <present>yes</present>
      <aspect>16:9</aspect>
      <quality>HDTV</quality>
    </video>
    <audio>
      <present>yes</present>
      <stereo>stereo</stereo>
    </audio>
      <new />
  </programme>`

**Comment by mpoplaw** [comment]
I am refreshing guide data on plex using 0.5.16 now.  I see that dd_progid is now used in this version.

**Comment by mpoplaw** [comment]
0.5.16 still had the 8/22/05 news episode and +0000 in <episode-num>.   I then installed 0.5.15 and I no longer see +0000, and the episode number (date) was back to being off by the difference in timezone :  -6000.

So it looks like adding +0000 is not working like we thought.

**Comment by mpoplaw** [comment]
A couple more ideas for formatting the time...
`<episode-num system="original-air-date">2021-01-22 00:00:00+0000</episode-num>`
or
`<episode-num system="original-air-date">2021-01-22 "00:00:00 +0000"</episode-num>`

what do you think?

**Comment by wouterdebie** [comment]
The stuff we did with the original-air-date might actually be a bit of a hack. Maybe we should try it just with dd_progid and see what happens? Could you provide me your config (especially zip codes) and what program you're looking at to validate if it works or not?

**Comment by mpoplaw** [comment]
I run locastdvr via (user & pass removed):
`locast2dvr --multiplex --override-zipcodes=55410`

I am validating with PLEX Media Server.  I'll see if I can experiment on my side over the weekend as well.   Thanks.

**Comment by wouterdebie** [comment]
I think I fixed the timezone offset in 0.6.0. I couldn't figure out how to tell Plex what timezone the timestamp was in, so I added timezone support in locast2dvr. Based on the lat/long of the DMA, I'll lookup the timezone and use that to offset the startTime of the broadcast. I've tested it with Plex and it seems to work.

**Comment by mpoplaw** [comment]
I made a similar change over the weekend to get this working, but yours is much more elegant.   Looks good and works great, at least until PLEX changing something on their side.  Thank you again!

**Comment by wouterdebie** [comment]
My pleasure and thanks for having a look! I'll close this issue for now.
