### ISSUE TITLE
Anyone have a guide for newbs to set this up?

### ISSUE THREAD

**Issue by eqpaisley** [wouterdebie/locast2dvr#22]
Trying to follow the instructions but cannot get this installed. 

`pip install locast2dvr`

gives me

```
Could not find a version that satisfies the requirement locast2dvr (from versions: )
No matching distribution found for locast2dvr
```
And if I  `git clone ` the repository, locast2dvr is not an executable.

**Comment by wouterdebie** [comment]
What python version are you using? You need python 3.7 or higher.

**Comment by eqpaisley** [comment]
3.7 is installed   I just updated my python alternatives to see if that's the issue but that didn't work either.  Does this have to be cloned before using `pip install` ?  It doesn't say that in the install instructions.

**Comment by eqpaisley** [comment]
Following up. Here's what I am seeing when I try to install:

```
root@Fermi-Plex:/home/kilgoretrout# pip install `locast2dvr`
locast2dvr: command not found
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
ERROR: You must give at least one requirement to install (see "pip help install")
```
I do have python3.79 installed but when I `python --version`  it still tells me 3.6.9
