### ISSUE TITLE
Offset the EPG?

### ISSUE THREAD

**Issue by eqpaisley** [wouterdebie/locast2dvr#23]
With the ability to have multiple instances from different time zones running, it would be useful to have the ability to offset the guide.  If I load LA stations and NYC stations into Emby (Jellyfin) and it's 6pm server time, the LA stations will be off (or vice versa)

**Comment by wouterdebie** [comment]
All times in the epg are in UTC, so they should be ok.

**Comment by eqpaisley** [comment]
Ok thanks!
