### ISSUE TITLE
Plex: Could not tune channel. Please check your tuner or antenna.

### ISSUE THREAD

**Issue by TheSamDickey** [wouterdebie/locast2dvr#27]
Hello!  I am running locast2dvr using the recommended python venv method.  Everything seemed to be working great.  All the channels popped up, and I was able to use the xml file to get all the stations added properly.

Whenever I try to watch any of the channels plex loads for a few seconds and then says: "Could not tune channel. Please check your tuner or antenna."

I manually downloaded ffmpeg-4.3.2-amd64-static and put the ffmpeg file into a folder.  I used the --ffmpeg flag to specify its location, and the script says Using ffmpeg.  I wonder if someone is using a different version of ffmpeg that works?

This is amazing software, thank you so much for putting a lot of effort into making this!

**Comment by wouterdebie** [comment]
Hi!

Would you mind adding some logs to this ticket? FFmpeg is not strictly
necessary if you use the direct mode.

**Comment by TheSamDickey** [comment]
Sure!  Where are the logs located?  

And I wasn't sure from the readme if direct mode could work with Plex.  If it does, it seems a lot more efficient to do it that way

**Comment by wouterdebie** [comment]
I should yes.. let me know if that works!

**Comment by TheSamDickey** [comment]
Alright so I've ran it with the direct flag and added it to plex.  It still has the same problem.

I enabled the verbose mode and it gave me this:
```
Traceback (most recent call last):
  File "/home/user/Documents/locast2dvr/venv/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/user/Documents/locast2dvr/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 727, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/user/Documents/locast2dvr/venv/lib/python3.7/site-packages/urllib3/util/retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.locastnet.org', port=443): Max retries exceeded with url: /api/watch/station/1816/29.80675/-95.56243 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2d2542b898>: Failed to establish a new connection: [Errno -2] Name or service not known'))
```

Do you think it could be a problem with locast not thinking I'm in the right dma zone?

**Comment by TheSamDickey** [comment]
[log.txt](https://github.com/wouterdebie/locast2dvr/files/6216781/log.txt)
Here is a log file by the way

**Comment by wouterdebie** [comment]
It seems locast2dvr can't find api.locastnet.org. what happens when you
type that into your browser?

**Comment by TheSamDickey** [comment]
I get "503 Service Temporarily Unavailable" when I put it into my browser.

**Comment by wouterdebie** [comment]
Would you mind sharing your config? Are you in a locast region? And if not,
what do you override? Are there any proxies you or you ISP are using? The
problem seems to be with your connection to locast, rather than locast2dvr.

**Comment by wouterdebie** [comment]
Actually, I take that back.. the API connection gives a 503 for me as well,
which is fine.
However it seems that the host you're running locast2dvr on can't lookup
the proper name.

**Comment by TheSamDickey** [comment]
I wouldn't mind sending my config, but could I send it to you through discord or something else?

I was messing around with this all day yesterday and also set up software called telly.  It's an IPTV proxy for Plex, and I read through a discussion on reddit where someone got it to work with locast2plex.  Anyways, when I point telly to locast2dvr it behaves the exact same where Plex says that it could not tune the channel.

I have two networks; one is 192.168.0.0/24 and the other is 192.168.1.0/24.  Plex/telly are on 192.168.0.0/24 and Locast2plex runs on 192.168.1.0/24.  The computer with Locast2plex is behind a pfsense NAT.

I know now after messing with this all that Telly is entirely unnecessary, but it does give me an interesting log.  Here is a log from Telly:
```
time="2021-03-28T03:29:30Z"` level=info msg=" built with gcc 9.3.0 (Alpine 9.3.0)"
time="2021-03-28T03:29:30Z" level=info msg=" configuration: --disable-debug --disable-doc --disable-ffplay --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-libass --enable-fontconfig --enable-libfreetype --enable-libvidstab --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libxcb --enable-libx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-postproc --enable-small --enable-version3 --enable-libbluray --enable-libzmq --extra-libs=-ldl --prefix=/opt/ffmpeg --enable-libopenjpeg --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-libsrt --extra-cflags=-I/opt/ffmpeg/include --extra-ldflags=-L/opt/ffmpeg/lib"
time="2021-03-28T03:29:30Z" level=info msg=" libavutil 56. 14.100 / 56. 14.100"
time="2021-03-28T03:29:30Z" level=info msg=" libavcodec 58. 18.100 / 58. 18.100"
time="2021-03-28T03:29:30Z" level=info msg=" libavformat 58. 12.100 / 58. 12.100"
time="2021-03-28T03:29:30Z" level=info msg=" libavdevice 58. 3.100 / 58. 3.100"
time="2021-03-28T03:29:30Z" level=info msg=" libavfilter 7. 16.100 / 7. 16.100"
time="2021-03-28T03:29:30Z" level=info msg=" libavresample 4. 0. 0 / 4. 0. 0"
time="2021-03-28T03:29:30Z" level=info msg=" libswscale 5. 1.100 / 5. 1.100"
time="2021-03-28T03:29:30Z" level=info msg=" libswresample 3. 1.100 / 3. 1.100"
time="2021-03-28T03:29:30Z" level=info msg=" libpostproc 55. 1.100 / 55. 1.100"
time="2021-03-28T03:29:35Z" level=info msg="http://192.168.1.100:6077/watch/339.m3u: Operation timed out"
time="2021-03-28T03:29:35Z" level=info msg="Stopped streaming 10000"
time="2021-03-28T03:29:35Z" level=info msg="Stopped streaming 10000"
http: superfluous response.WriteHeader call from github.com/gin-gonic/gin.(*responseWriter).WriteHeaderNow (response_writer.go:70)
time="2021-03-28T22:03:46Z" level=info msg="Serving channel number 10017"
time="2021-03-28T22:03:46Z" level=info msg="Remuxing stream with ffmpeg"
```

What I found interesting is where it says `msg="http://192.168.1.100:6077/watch/339.m3u: Operation timed out"`  Because 192.168.1.100 does not go anywhere for Telly, does that mean that the problem is a lan networking issue?

The computer running locast2plex is on an entire different subnet than the computer hosting telly/plex, and 192.168.1.100 is not directly visible from the telly/plex.  I have ports forwarded so that locast2dvr is exposed on 192.168.0.156.

What does the --bind-address mean?  Should it be set to something other than the computer's own ip address?

**Comment by wouterdebie** [comment]
Are you sure that your routing/firewalling is ok? Can you reach the outside
world from the box that is running locast2dvr? Can both your subnets freely
connect to each other?  Bind address should be set to the IP your
telly/plex/emby wants to connect to as it defaults to 127.0.0.1.
Tbh, I'm suspicious of your network setup, since telly can't connect to
locast2dvr and locast2dvr has a hard time resolving api.locastnet.org. Can
you from 192.168.0.0/24 reach http://192.168.1.100:6077/watch/339.m3u?
(e.g. curl http://192.168.1.100:6077/watch/339.m3u) and can you reach
https://api.locastnet.org (e.g. curl http://192.168.1.100:6077/watch/339.m3u
)?

For the config: you can download your config with masked password using
http://192.168.1.100:6077/ <http://192.168.1.100:6077/watch/339.m3u>config.
I don't have discord, but you can send me an email at github at evenflow
dot nl.

**Comment by TheSamDickey** [comment]
I was fairly certain that my network was sound, everything seemed to work fine.  I simplified things by removing telly and putting it all on the same network and now it works great!  

Thank you so much for the help, I really appreciate it!! :D
